import { type NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";
import { t_portfolios } from "@prisma/client";
import { Box, Button, ButtonGroup, Card, Stack, Typography } from "@mui/material";

export const getServerSideProps = async () => {
  const portfolios = await prisma.t_portfolios.findMany({})
  return ({
    props: {
      portfolios
    }
  })
}

const Home: NextPage<{ portfolios: t_portfolios[] }> = (props) => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack direction="row" justifyContent={"center"}>

        <Card sx={{ padding: 8, gap: 4, grow: 0, maxWidth: 500, display: "flex", flexDirection: "column", alignItems: "center" }}>
          <Typography variant="h4" sx={{ textAlign: "center" }}>Choose a portfolio</Typography>
          <Box>
            <ButtonGroup orientation="vertical">
              {props.portfolios.map((portfolio) => (
                <Button variant="contained" key={portfolio.id} href={"/portfolio/" + portfolio.id}>
                  {portfolio.name}
                </Button>
              ))}
            </ButtonGroup>
          </Box>
        </Card>
      </Stack>
    </>
  );
};

export default Home;
